#:schema ../extra/schemas/color-theme.json

[color-theme]
name = "Texas Dark"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]
black = "#1F1F1F"
blue = "#569CD6"
cyan = "#4EC9B0"
green = "#6A9955"
grey = "#3C3C3C"
magenta = "#C586C0"
orange = "#CE9178"
purple = "#C586C0"
red = "#F85149"
white = "#CCCCCC"
yellow = "#DCDCAA"
primary-background = "#1F1F1F"
secondary-background = "#181818"
current-background = "#2B2B2B"
text = "#CCCCCC"
dim-text = "#9D9D9D"

[color-theme.syntax]
"comment" = "$green"
"constant" = "#4FC1FF"
"type" = "$cyan"
"typeAlias" = "$cyan"
"number" = "#B5CEA8"
"enum" = "$cyan"
"struct" = "$cyan"
"structure" = "$cyan"
"interface" = "$cyan"
"attribute" = "#4EC9B0"
"constructor" = "$yellow"
"function" = "$yellow"
"method" = "$yellow"
"function.method" = "$yellow"
"keyword" = "$blue"
"selfKeyword" = "#569CD6"
"field" = "#9CDCFE"
"property" = "#9CDCFE"
"enumMember" = "#4FC1FF"
"enum-member" = "#4FC1FF"
"string" = "$orange"
"type.builtin" = "#4EC9B0"
"builtinType" = "#4EC9B0"
"escape" = "#D7BA7D"
"string.escape" = "#D7BA7D"
"embedded" = "#D4D4D4"
"punctuation.delimiter" = "#D4D4D4"
"text.title" = "#569CD6"
"text.uri" = "#4DAAFC"
"text.reference" = "$yellow"
"variable" = "#9CDCFE"
"variable.other.member" = "#9CDCFE"
"tag" = "#569CD6"
"markup.heading" = "#569CD6"
"markup.bold" = "#569CD6"
"markup.italic" = "#C586C0"
"markup.list" = "#6796E6"
"markup.link.url" = "#4DAAFC"
"markup.link.label" = "#4DAAFC"
"markup.link.text" = "#4DAAFC"
"bracket.color.1" = "$yellow"
"bracket.color.2" = "$purple"
"bracket.color.3" = "$blue"
"bracket.unpaired" = "$red"

[color-theme.ui]
"texas.error" = "$red"
"texas.warn" = "#E2C08D"
"texas.dropdown_shadow" = "#010409"
"texas.border" = "#2B2B2B"
"texas.scroll_bar" = "#868686"
"texas.tab.active.underline" = "#0078D4"
"texas.tab.inactive.underline" = "#2B2B2B"
"texas.icon.active" = "#CCCCCC"
"texas.icon.inactive" = "#868686"
"editor.background" = "$primary-background"
"editor.foreground" = "$text"
"editor.dim" = "$dim-text"
"editor.focus" = "#FFFFFF"
"editor.caret" = "#0078D4"
"editor.selection" = "#3A3D41"
"editor.current_line" = "$current-background"
"editor.link" = "#4DAAFC"
"editor.visible_whitespace" = "#FFFFFF17"
"editor.indent_guide" = "#404040"
"editor.drag_drop_background" = "#ADD6FF26"
"editor.sticky_header_background" = "$primary-background"
"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#F1F1F133"
"source_control.added" = "#2EA043"
"source_control.removed" = "#F85149"
"source_control.modified" = "#0078D4"
"tooltip.background" = "#202020"
"tooltip.foreground" = "$text"
"palette.background" = "#222222"
"palette.current.background" = "#2B2B2B"
"hover.background" = "#2B2B2B"
"panel.background" = "$secondary-background"
"panel.foreground" = "#CCCCCC"
"panel.foreground.dim" = "#9D9D9D"
"panel.current.background" = "#37373D"
"panel.hovered.background" = "#2B2B2B"
"panel.hovered.active.background" = "#37373D"
"status.background" = "#181818"
"status.foreground" = "#CCCCCC"
"status.modal.normal.background" = "#0078D4"
"status.modal.normal.foreground" = "$primary-background"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$primary-background"
"status.modal.visual.background" = "#E2C08D"
"status.modal.visual.foreground" = "$primary-background"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$primary-background"
"terminal.cursor" = "#0078D4"
"terminal.foreground" = "#CCCCCC"
"terminal.background" = "$primary-background"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "$white"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "$dim-text"
