#:schema ../extra/schemas/color-theme.json

[color-theme]
name = "Texas Light"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]
black = "#3B3B3B"
blue = "#0000FF"
cyan = "#267F99"
green = "#008000"
grey = "#CECECE"
magenta = "#AF00DB"
orange = "#A31515"
purple = "#AF00DB"
red = "#F85149"
white = "#FFFFFF"
yellow = "#795E26"
primary-background = "#FFFFFF"
secondary-background = "#F8F8F8"
current-background = "#E5E5E5"
text = "#3B3B3B"
dim-text = "#616161"

[color-theme.syntax]
"comment" = "$green"
"constant" = "#0070C1"
"type" = "$cyan"
"typeAlias" = "$cyan"
"number" = "#098658"
"enum" = "$cyan"
"struct" = "$cyan"
"structure" = "$cyan"
"interface" = "$cyan"
"attribute" = "#267F99"
"constructor" = "$yellow"
"function" = "$yellow"
"method" = "$yellow"
"function.method" = "$yellow"
"keyword" = "$blue"
"selfKeyword" = "#0000FF"
"field" = "#001080"
"property" = "#001080"
"enumMember" = "#0070C1"
"enum-member" = "#0070C1"
"string" = "$orange"
"type.builtin" = "#267F99"
"builtinType" = "#267F99"
"escape" = "#EE0000"
"string.escape" = "#EE0000"
"embedded" = "#000000FF"
"punctuation.delimiter" = "#000000"
"text.title" = "#800000"
"text.uri" = "#005FB8"
"text.reference" = "$yellow"
"variable" = "#001080"
"variable.other.member" = "#001080"
"tag" = "#800000"
"markup.heading" = "#800000"
"markup.bold" = "#000080"
"markup.italic" = "#800080"
"markup.list" = "#0451A5"
"markup.link.url" = "#005FB8"
"markup.link.label" = "#005FB8"
"markup.link.text" = "#005FB8"
"bracket.color.1" = "$yellow"
"bracket.color.2" = "$purple"
"bracket.color.3" = "$blue"
"bracket.unpaired" = "$red"

[color-theme.ui]
"texas.error" = "$red"
"texas.warn" = "#895503"
"texas.dropdown_shadow" = "#E5E5E5"
"texas.border" = "#E5E5E5"
"texas.scroll_bar" = "#616161"
"texas.tab.active.underline" = "#005FB8"
"texas.tab.inactive.underline" = "#E5E5E5"
"texas.icon.active" = "#3B3B3B"
"texas.icon.inactive" = "#616161"
"editor.background" = "$primary-background"
"editor.foreground" = "$text"
"editor.dim" = "$dim-text"
"editor.focus" = "#3B3B3B"
"editor.caret" = "#005FB8"
"editor.selection" = "#E5EBF1"
"editor.current_line" = "$current-background"
"editor.link" = "#005FB8"
"editor.visible_whitespace" = "#E5E5E5"
"editor.indent_guide" = "#D3D3D3"
"editor.drag_drop_background" = "#ADD6FF80"
"editor.sticky_header_background" = "$primary-background"
"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#1F1F1F11"
"source_control.added" = "#2EA043"
"source_control.removed" = "#F85149"
"source_control.modified" = "#005FB8"
"tooltip.background" = "#F8F8F8"
"tooltip.foreground" = "$text"
"palette.background" = "#F8F8F8"
"palette.current.background" = "#CCCCCC"
"hover.background" = "#CCCCCC"
"panel.background" = "$secondary-background"
"panel.foreground" = "#3B3B3B"
"panel.foreground.dim" = "#3B3B3B"
"panel.current.background" = "#E4E6F1"
"panel.hovered.background" = "#CCCCCC"
"panel.hovered.active.background" = "#E4E6F1"
"status.background" = "#F8F8F8"
"status.foreground" = "#3B3B3B"
"status.modal.normal.background" = "#005FB8"
"status.modal.normal.foreground" = "$primary-background"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$primary-background"
"status.modal.visual.background" = "#895503"
"status.modal.visual.foreground" = "$primary-background"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$primary-background"
"terminal.cursor" = "#005FB8"
"terminal.foreground" = "#3B3B3B"
"terminal.background" = "$primary-background"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "$white"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "$dim-text"
