#:schema ../extra/schemas/settings.json

[core]
modal = false
color-theme = "Texas Dark"
icon-theme = "Texas Codicons"
custom-titlebar = true
file-explorer-double-click = false

[editor]
font-family = "Cascadia Mono, Consolas, 'Courier New', monospace"
font-size = 13
line-height = 1.5
smart-tab = true
tab-width = 4
show-tab = true
show-bread-crumbs = true
scroll-beyond-last-line = true
cursor-surrounding-lines = 1
wrap-style = "editor-width"
wrap-width = 600                                             # px
sticky-header = true
auto-closing-matching-pairs = true
auto-surround = true
modal-mode-relative-line-numbers = true
highlight-matching-brackets = true
highlight-scope-lines = false
autosave-interval = 0
normalize-line-endings = true
blink-interval = 500                                         # ms
multicursor-case-sensitive = true
multicursor-whole-words = true
render-whitespace = "none"
show-indent-guide = true
atomic-soft-tabs = false
double-click = "single"
bracket-pair-colorization = false
bracket-colorization-limit = 30000
files-exclude = "**/{.git,.svn,.hg,CVS,.DS_Store,Thumbs.db}" # Glob patterns

[terminal]
font-family = ""
font-size = 0
line-height = 0

[terminal.default-profile]
macos = "default"
linux = "default"
windows = "default"

[terminal.profiles]
default = {}

# [terminal.profiles.example]
# command     = "cargo"
# arguments   = ["run"]
# environment = { "KEY" = "VALUE" }
# workdir     = "/home/user"

[ui]
language = "auto"
scale = +1.0
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-separator-height = "Content"
palette-width = 500
trim-search-results-whitespace = true
tab-close-button = "Right"
open-editors-visible = true
